### ISSUE TITLE
Header color not working for Header 1 and 2

### ISSUE THREAD

**Issue by b1uegh0st** [calrobertlee/roam-css-styles#21]
Hi, 

I am using Nox as imported or copied.

Here is the resulting color
![image](https://user-images.githubusercontent.com/6695697/103526436-7ee54800-4eb3-11eb-8b68-f934860451af.png)

Here is the inspection for header 1
![image](https://user-images.githubusercontent.com/6695697/103526716-e8fded00-4eb3-11eb-9615-0c2390de17ff.png)

Here is the inspection for header 3
![image](https://user-images.githubusercontent.com/6695697/103527243-9e30a500-4eb4-11eb-86d3-ad994063c1e2.png)

If I understand correctly:
- The CSS code should result in all header levels sharing same color
![image](https://user-images.githubusercontent.com/6695697/103527005-47c36680-4eb4-11eb-888e-c5d8227a9dc0.png)

- Somehow only header 3 got the color.

Thanks for making the theme.
NA

**Comment by b1uegh0st** [comment]
Also, tried to play around with Lux theme a bit. If I delete this part it seems to change the color of the page title, not header level1.

`/* H1 COLOR */
.roam-body .roam-app h1 {
    color: var(--h1-font-color);
}`

**Comment by b1uegh0st** [comment]
Update, changed the code to include full as in the inspection line. It works now.

```css
/* H1 */
.rm-level1, .rm-heading-level-1 > .rm-block__self .rm-block__input {
    /* font-family: 'Inter', sans-serif !important; */
    font-weight: 400;
    font-size: 1.8em;
    font-family: var(--main-font);
    color: var(--h1-font-color);
    /* margin-top: -5px !important; */
}
/* H2 */
.rm-level2, .rm-heading-level-2 > .rm-block__self .rm-block__input {
    /* font-family: 'Inter', sans-serif !important; */
    font-weight: 400;
    font-size: 1.4em;
    font-family: var(--main-font);
    color: var(--h2-font-color);
    /* margin-top: -5px !important; */
}
```
