### ISSUE TITLE
Dark (Nox) block embed still light

### ISSUE THREAD

**Issue by b1uegh0st** [calrobertlee/roam-css-styles#26]
Not a terribly inconvenience for me (I haven't used a lot of block embeds) but would like to note here for you. The embedded reference are still in light-mode.

![image](https://user-images.githubusercontent.com/6695697/109809674-2afca280-7c5b-11eb-964e-372434289dd3.png)

Copy what I am seeing inspect
![image](https://user-images.githubusercontent.com/6695697/109809951-8169e100-7c5b-11eb-9316-55074e947027.png)

**Comment by b1uegh0st** [comment]
Sorry for the pointer, rm-inline-reference

**Comment by b1uegh0st** [comment]
FYI to temporary fix it, I am temporarily using this:

``` css
.rm-nested-refs {
  background-color: #002b80;}
.rm-inline-references {
  background-color: #002b80;}
.rm-block__self .rm-block__ref-count.rm-active {
    opacity: 1;
    color: #8A9BA8;
  background-color: #002b80;} 
```

before:
![image](https://user-images.githubusercontent.com/6695697/112721850-b99dd000-8f38-11eb-9398-5b0e301a909d.png)

after:
![image](https://user-images.githubusercontent.com/6695697/112721861-c91d1900-8f38-11eb-9cc3-82e42212acd5.png)
